system:
    random_seed: 8
    num_workers: 8
    num_gpus: 1
paths:
    tensorboard_dir: /home/levi/Data_work/workplace/Geobyoc-main/tensor_logs
    experiments_dir: /home/levi/Data_work/workplace/Geobyoc-main/experiments
train:
    num_steps: 400000
    eval_step: 5000
    vis_step: 1000
    optimizer: Adam
    lr: 0.0001
    momentum: 0.9
    weight_decay: 1e-6
test:
    checkpoint:
        name: "GeoBYOC"
        time: timeless
        epoch: 0
        step: -1
    split: test
    align_cfg:
        algorithm: weighted_procrustes
        num_correspodances: 200
        point_ratio: 0.05
        num_seeds: 100
        loss_weighting: lowe

coarse_loss:
    positive_margin: 0.1
    negative_margin: 1.4
    positive_optimal: 0.1
    negative_optimal: 1.4
    log_scale: 24
    positive_overlap: 0.1

fine_loss:
    positive_radius: 0.5

loss:
    weight_coarse_loss: 1.0
    weight_fine_loss: 1.0

defaults:
    - model: byoc
    - dataset: 3DMatch
