system:
    random_seed: 8
    num_workers: 8
    num_gpus: 1
paths:
    tensorboard_dir: /home/levi/Data_work/workplace/RGBD_PCL/tensor_logs
    experiments_dir: /home/levi/Data_work/workplace/RGBD_PCL/experiments
train:
    num_steps: 400000
    eval_step: 5000
    vis_step: 5000
    optimizer: Adam
    lr: 1e-4
    lr_decay_steps: 20000
    lr_decay: 0.95
    momentum: 0.9
    weight_decay: 1e-6

test:
    checkpoint:
        name: "urr_overlap_geobyoc_20"
        time: "03190734"
        epoch: 0
        step: -1
    split: test

coarse_loss:
    positive_margin: 0.1
    negative_margin: 1.4
    positive_optimal: 0.1
    negative_optimal: 1.4
    log_scale: 24
    positive_overlap: 0.1
fine_loss:
    positive_radius: 0.05

loss:
    weight_coarse_loss: 1.0
    weight_fine_loss: 1.0

eval:
    acceptance_overlap: 0.1
    acceptance_radius: 0.03
    rmse_threshold: 0.2

defaults:
    - model: GeoRGBD
    - dataset: 3DMatch
